[FakeDataValidConfig]

[FakeDataValidConfig.Enu]

title = "Enu"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [200, 0, 10]
]

axis_titles = [
      "#it{E_{#nu}} (GeV)",
      "d#sigma/d#it{E_{#nu}} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.PLep]

title = "PLep"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [200, 0, 10]
]

axis_titles = [
      "#it{p}_{lep} (GeV/#it{c})",
      "d#sigma/d#it{p}_{lep} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.q0]

title = "q0"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 3]
]

axis_titles = [
      "q_{0} (GeV)",
      "d#sigma/dq_{0} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.q3]

title = "q3"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 3]
]

axis_titles = [
      "q_{3} (GeV/#it{c})",
      "d#sigma/dq_{3} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.ThetaLep]

title = "ThetaLep"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 3.1415927]
]

axis_titles = [
      "#theta_{lep} (GeV)",
      "d#sigma/d#theta_{lep} cm^{2} rad^{-1}"
]

[FakeDataValidConfig.EAvHad]

title = "EAvHad"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 5]
]

axis_titles = [
      "it{E}_{had}^{vis} (GeV)",
      "d#sigma/d#it{E}_{had}^{vis} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.PtLep]

title = "PtLep"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 2]
]

axis_titles = [
      "#{p}^{T}_{lep} (GeV)",
      "d#sigma/d#{p}^{T}_{lep} cm^{2} GeV^{-1} #it{c}"
]
