[FakeDataValidConfig]

EnuCut = 10.0

[FakeDataValidConfig.Enu]

title = "Enu"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC0pi", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

x_binning = [
      "var",
      [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45,
        0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85,
        0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2,
        2.2, 2.4, 2.6, 2.8, 3, 3.25, 3.5, 3.75 , 4,
        4.25, 4.5, 4.75, 5, 5.5, 6, 6.5,
        7, 8, 9, 10
      ]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "d#sigma/d#it{E}_{#nu}cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.EnuERecQEBias]

title = "EnuERecQEBias"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC0pi", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

x_binning = [
      "var",
      [0.0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5]
]

y_binning = [
      "uniform",
      [100,-1,1]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "#it{E}_{Rec. Bias}^{QE}",
      "d#sigma/d#it{E}_{#nu}#it{E}_{Rec. Bias}^{QE} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.EnuERecAvBias]

title = "EnuERecAvBias"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC0pi", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

x_binning = [
      "var",
      [0.0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5]
]

y_binning = [
      "uniform",
      [80,-0.3,0.1]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "#it{E}_{Rec. Bias}^{Had. Av.}",
      "d#sigma/d#it{E}_{#nu}#it{E}_{Rec. Bias}^{Had. Av.} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.Q2]

title = "Q2"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC0pi", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

x_binning = [
      "uniform",
      [100,0,3]
]

axis_titles = [
      "#it{Q}^{2} (GeV^{2})",
      "d#sigma/d#it{Q}^{2} cm^{2} GeV^{-2}"
]

[FakeDataValidConfig.q0]
title = "q0"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC0pi", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

x_binning = [
      "uniform",
      [100,0,3]
]

axis_titles = [
      "q_{0} (GeV)",
      "d#sigma/dq_{0} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.yrec]
title = "yrec"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC0pi", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

x_binning = [
      "uniform",
      [100,0,1]
]

axis_titles = [
      "y_{Rec}",
      "d#sigma/dy_{Rec} cm^{2}"
]

[FakeDataValidConfig.Enuyrec]
title = "Enuyrec"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC0pi", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

y_binning = [
      "uniform",
      [100,0,1]
]

x_binning = [
      "var",
      [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45,
        0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85,
        0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2,
        2.2, 2.4, 2.6, 2.8, 3, 3.25, 3.5, 3.75 , 4,
        4.25, 4.5, 4.75, 5, 5.5, 6, 6.5,
        7, 8, 9, 10
      ]
]
      
axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "y_{Rec}",
      "d#sigma/d#it{E}_{#nu}y_{Rec} cm^{2} GeV^{-1} "
]

[FakeDataValidConfig.PLep]

title = "PLep"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", ]

x_binning = [
      "uniform",
      [200,0,10]
]

axis_titles = [
      "#it{p}_{lep} (GeV/#it{c})",
      "d#sigma/d#it{p}_{lep} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.PtLep]

title = "PtLep"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", ]

x_binning = [
      "uniform",
      [40,0,2]
]

axis_titles = [
      "#it{p}^{T}_{lep} (GeV/#it{c})",
      "d#sigma/d#it{p}^{T}_{lep} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.EAvHad]

title = "EAvHad"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", ]

x_binning = [
      "uniform",
      [100, 0, 10]
]

axis_titles = [
      "#it{E}_{Had}^{Vis} (GeV)",
      "d#sigma/d#it{E}_{Had}^{Vis} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.EnuEAvHad]

title = "EnuEAvHad"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", ]

x_binning = [
      "var",
      [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45,
        0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85,
        0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2,
        2.2, 2.4, 2.6, 2.8, 3, 3.25, 3.5, 3.75 , 4,
        4.25, 4.5, 4.75, 5, 5.5, 6, 6.5,
        7, 8, 9, 10
      ]
]

y_binning = [
      "uniform",
      [50, 0, 4]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "#it{E}_{Had}^{Vis} (GeV)",
      "d#sigma/d#it{E}_{#nu}#it{E}_{Had}^{Vis} cm^{2} GeV^{-2}"
]

[FakeDataValidConfig.q0q3_low]

title = "q0q3_low"
selections = ["CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "NC1pi0" ]

x_binning = [
      "uniform",
      [100, 0, 1.2]
]

y_binning = [
      "uniform",
      [100, 0, 1.2]
]

axis_titles = [
      "q_{3} (GeV/#it{c})",
      "q_{0} (GeV)",
      "d#sigma/dq_{0}q_{3} cm^{2} GeV^{-2} #it{c}"
]

[FakeDataValidConfig.q0q3_high]

title = "q0q3_high"
selections = ["CCInc", "CCInc_RW", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", "NCInc", "NCInc_RW", "NC1Gamma", "NCDeExciteGamma", "NCNGamma", "NC1cpi", "NC1pi0", "NCmultipi", "NCOther", "NCOther_QE", ]

x_binning = [
      "uniform",
      [100, 0, 3]
]

y_binning = [
      "uniform",
      [100, 0, 3]
]

axis_titles = [
      "q_{3} (GeV/#it{c})",
      "q_{0} (GeV)",
      "d#sigma/dq_{0}q_{3} cm^{2} GeV^{-2} #it{c}"
]

[FakeDataValidConfig.ThetaLep]

title = "ThetaLep"
selections = ["CCInc", "CCInc_RW", "CC0pi", "CC0pi_QE", "CC0pi_2p2h", "CC0pi_Other", "CC1Gamma", "CCDeExciteGamma", "CCNGamma", "CC1cpi", "CC1pi0", "CCmultipi", "CCOther", "CCOther_QE", ]

x_binning = [
      "uniform",
      [30, 0, 180]
]

axis_titles = [
      "#theta_{lep} (GeV)",
      "d#sigma/d#theta_{lep} cm^{2} deg^{-1}"
]

[FakeDataValidConfig.hmfscpip]

title = "hmfscpip"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1cpi", "CCmultipi", "CCOther", "NC1cpi", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [50,1E-8,1.5]
]

axis_titles = [
      "#it{p}_{#pi^{#pm}} (GeV)",
      "d#sigma/d#it{p}_{#pi^{#pm}} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.hmfspi0p]

title = "hmfspi0p"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1pi0", "CCmultipi", "CCOther", "NC1pi0", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [50,1E-8,1.5]
]

axis_titles = [
      "#it{p}_{#pi^{0}} (GeV)",
      "d#sigma/d#it{p}_{#pi^{0}} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.ncpi]

title = "ncpi"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1cpi", "CCmultipi", "CCOther", "NC1cpi", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [6, 0, 6]
]

axis_titles = [
      "N_{#pi^{#pm}}",
      "d#sigma/dN_{#pi^{#pm}} cm^{2}"
]

[FakeDataValidConfig.npi0]

title = "npi0"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1pi0", "CCmultipi", "CCOther", "NC1pi0", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [5, 0, 5]
]

axis_titles = [
      "N_{#pi^{0}}",
      "d#sigma/dN_{#pi^{0}} cm^{2}"
]

[FakeDataValidConfig.hmfsprotonp]

title = "hmfsprotonp"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1cpi", "CCmultipi", "CCOther", "NC1cpi", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [50,1E-8,1.5]
]

axis_titles = [
      "#it{p}_{p^{+}} (GeV)",
      "d#sigma/d#it{p}_{p^{+}} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.hmfsneutronp]

title = "hmfsneutronp"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1pi0", "CCmultipi", "CCOther", "NC1pi0", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [50,1E-8,1.5]
]

axis_titles = [
      "#it{p}_{n} (GeV)",
      "d#sigma/d#it{p}_{n} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.nproton]

title = "nproton"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1cpi", "CCmultipi", "CCOther", "NC1cpi", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [8, 0, 8]
]

axis_titles = [
      "N_{p^{+}}",
      "d#sigma/dN_{p^{+}} cm^{2}"
]

[FakeDataValidConfig.nneutrons]

title = "nneutrons"
selections = [ "CCInc", "NCInc", "CCInc_RW", "NCInc_RW", "CC1pi0", "CCmultipi", "CCOther", "NC1pi0", "NCmultipi", "NCOther", ]

x_binning = [
      "uniform",
      [8, 0, 8]
]

axis_titles = [
      "N_{#pi^{0}}",
      "d#sigma/dN_{#pi^{0}} cm^{2}"
]

[FakeDataValidConfig.EGamma]

title = "EGamma"
selections = [ "CCInc", "CCInc_RW", "NCInc", "NCInc_RW", "CC1Gamma", "CCNGamma", "CCOther", "NC1Gamma", "NCNGamma", "NCOther", ]

x_binning = [
      "uniform",
      [100,1E-6,1]
]

axis_titles = [
      "#it{E}_{#gamma} (GeV)",
      "d#sigma/d#it{E}_{#gamma} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.EGamma_DeExcite]

title = "EGamma_DeExcite"
selections = ["CCDeExciteGamma", "NCDeExciteGamma", ]


x_binning = [
      "uniform",
      [25,1E-6,0.01]
]

axis_titles = [
      "#it{E}_{#gamma} (GeV)",
      "d#sigma/d#it{E}_{#gamma} cm^{2} GeV^{-1}"
]