[FakeDataValidConfig]

EnuCut = 20.0

[FakeDataValidConfig.Enu]

title = "Enu"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning_unif = [
      "uniform",
      [100, 0, 20]
]

x_binning = [
      "var",
      [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45,
            0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85,
            # 0.475, 0.5, 0.525, 0.55, 0.575, 0.6, 0.625, 0.65, 0.675, 0.7, 0.725, 0.75, 0.775, 0.8, 0.825, 0.85,
            0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2,
            2.2, 2.4, 2.6, 2.8, 3, 3.25, 3.5, 3.75 , 4,
            4.25, 4.5, 4.75, 5, 5.5, 6, 6.5,
            7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
      ]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "d#sigma/d#it{E}_{#nu} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.ERecQE]

title = "ERecQE"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning_unif = [
      "uniform",
      [100, 0, 20]
]

x_binning = [
      "var",
      [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45,
            0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85,
            # 0.475, 0.5, 0.525, 0.55, 0.575, 0.6, 0.625, 0.65, 0.675, 0.7, 0.725, 0.75, 0.775, 0.8, 0.825, 0.85,
            0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2,
            2.2, 2.4, 2.6, 2.8, 3, 3.25, 3.5, 3.75 , 4,
            4.25, 4.5, 4.75, 5, 5.5, 6, 6.5,
            7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
      ]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "d#sigma/d#it{E}_{#nu} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.Q2]

title = "Q2"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100,0,10]
]

axis_titles = [
      "#it{Q}^{2} (GeV^{2})",
      "d#sigma/d#it{Q}^{2} cm^{2} GeV^{-2}"
]

[FakeDataValidConfig.PLep]

title = "PLep"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [200,0,10]
]

axis_titles = [
      "#it{p}_{lep} (GeV/#it{c})",
      "d#sigma/d#it{p}_{lep} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.q0]

title = "q0"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 3]
]

axis_titles = [
      "q_{0} (GeV)",
      "d#sigma/dq_{0} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.q3]

title = "q3"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 3]
]

axis_titles = [
      "q_{3} (GeV/#it{c})",
      "d#sigma/dq_{3} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.q0q3]

title = "q0q3"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [50, 0, 2]
]

y_binning = [
      "uniform",
      [50, 0, 2]
]

axis_titles = [
      "q_{0} (GeV)",
      "q_{3} (GeV/#it{c})",
      "d#sigma/dq_{0}_{3} cm^{2} GeV^{-2} #it{c}"
]

[FakeDataValidConfig.ThetaLep]

title = "ThetaLep"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [30, 0, 180]
]

axis_titles = [
      "#theta_{lep} (GeV)",
      "d#sigma/d#theta_{lep} cm^{2} deg^{-1}"
]

[FakeDataValidConfig.EAvHad]

title = "EAvHad"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 5]
]

axis_titles = [
      "it{E}_{had}^{vis} (GeV)",
      "d#sigma/d#it{E}_{had}^{vis} cm^{2} GeV^{-1}"
]

[FakeDataValidConfig.PtLep]

title = "PtLep"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [100, 0, 2]
]

axis_titles = [
      "#it{p}^{T}_{lep} (GeV)",
      "d#sigma/d#it{p}^{T}_{lep} cm^{2} GeV^{-1} #it{c}"
]


[FakeDataValidConfig.EnuPLepThetaLep]

title = "EnuPLepThetaLep"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "var",
      [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45,
            0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85,
            # 0.475, 0.5, 0.525, 0.55, 0.575, 0.6, 0.625, 0.65, 0.675, 0.7, 0.725, 0.75, 0.775, 0.8, 0.825, 0.85,
            0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2,
            2.2, 2.4, 2.6, 2.8, 3, 3.25, 3.5, 3.75 , 4,
            4.25, 4.5, 4.75, 5, 5.5, 6, 6.5,
            7, 8, 9, 10
      ]
]

x_unif_binning = [
      "uniform",
      [100, 0, 20]
]

y_binning = [
      "uniform",
      [200, 0, 10]
]

z_binning = [
      "uniform",
      [30, 0, 180]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "#it{p}_{lep} (GeV/#it{c})",
      "#theta_{lep} (deg)",
      "GeV^{-2} #it{c} deg^{-1}"
]


[FakeDataValidConfig.EnuPLepEAvHad]

title = "EnuPLepEAvHad"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [60, 0, 20]
]

y_binning = [
      "uniform",
      [100, 0, 20]
]

z_binning = [
      "uniform",
      [100, 0, 10]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "#it{p}_{lep} (GeV/#it{c})",
      "#it{E}_{Had}^{Vis} (GeV)",
      "GeV^{-3} #it{c}"
]

[FakeDataValidConfig.EnuQ2EAvHad]

title = "EnuQ2EAvHad"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [60, 0, 20]
]

y_binning = [
      "uniform",
      [100, 0, 10]
]

z_binning = [
      "uniform",
      [100, 0, 10]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "Q^{2} (GeV^{2})",
      "#it{E}_{Had}^{Vis} (GeV)",
      "GeV^{-4} #it{c}"
]

[FakeDataValidConfig.EnuPtLepEAvHad]

title = "EnuPtLepEAvHad"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [60, 0, 20]
]

y_binning = [
      "uniform",
      [40,0,2]
]

z_binning = [
      "uniform",
      [100, 0, 10]
]

axis_titles = [
      "#it{E}_{#nu} (GeV)",
      "#it{p}^{T}_{lep} (GeV/#it{c})",
      "#it{E}_{Had}^{Vis} (GeV)",
      "GeV^{-4} #it{c}"
]


[FakeDataValidConfig.hmfscpip]

title = "hmfscpip"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [50,1E-8,1.5]
]

axis_titles = [
      "#it{p}_{#pi^{#pm}} (GeV)",
      "d#sigma/d#it{p}_{#pi^{#pm}} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.hmfspi0p]

title = "hmfspi0p"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [50,1E-8,1.5]
]

axis_titles = [
      "#it{p}_{#pi^{0}} (GeV)",
      "d#sigma/d#it{p}_{#pi^{0}} cm^{2} GeV^{-1} #it{c}"
]

[FakeDataValidConfig.ncpi]

title = "ncpi"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [6, 0, 6]
]

axis_titles = [
      "N_{#pi^{#pm}}",
      "d#sigma/dN_{#pi^{#pm}} cm^{2}"
]

[FakeDataValidConfig.npi0]

title = "npi0"
selections = [
      "CCInc",
      "CC0pi",
      "CC1Gamma",
      "CCNGamma",
      "CC1cpi",
      "CC1pi0",
      "CCmultipi",
      "CCOther",
      "NCInc",
      "NC0pi",
      "NC1Gamma",
      "NCNGamma",
      "NC1cpi",
      "NC1pi0",
      "NCmultipi",
      "NCOther",
]

x_binning = [
      "uniform",
      [5, 0, 5]
]

axis_titles = [
      "N_{#pi^{0}}",
      "d#sigma/dN_{#pi^{0}} cm^{2}"
]